# Generated by Django 4.2.3 on 2023-09-15 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('length', models.FloatField(verbose_name='Length')),
                ('breadth', models.FloatField(verbose_name='Breadth')),
                ('height', models.FloatField(verbose_name='Height')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Product Description')),
                ('image', models.ImageField(upload_to='products', verbose_name='Product Image')),
                ('price', models.FloatField(verbose_name='Product Price')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='account.company', verbose_name='Company')),
                ('shipping_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.shippinginfomodel', verbose_name='Shipping Info')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Category Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='categories', to='products.product')),
            ],
        ),
    ]
