# Generated by Django 4.2.3 on 2023-09-16 03:31

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfomodel',
            name='units',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=products.models.upload_path, verbose_name='Product Image'),
        ),
    ]
