# Generated by Django 4.2.3 on 2023-09-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_shippinginfomodel_units_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_info',
        ),
        migrations.AddField(
            model_name='product',
            name='breadth',
            field=models.FloatField(null=True, verbose_name='Breadth'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(null=True, verbose_name='Weight'),
        ),
        migrations.DeleteModel(
            name='ShippingInfoModel',
        ),
    ]
