# Generated by Django 4.2.3 on 2023-09-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category_products_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='breadth',
            field=models.CharField(max_length=500, null=True, verbose_name='Breadth'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(max_length=500, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.CharField(max_length=500, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=500, null=True, verbose_name='Weight'),
        ),
    ]
